-- Seed essential Bible verses so the Bible tab has data.
-- This is a minimal starter set across Old and New Testament.
INSERT INTO bible_verses (book, chapter, verse, text, testament, audio_url)
VALUES
  ('Genesis', 1, 1, 'In the beginning God created the heaven and the earth.', 'Old', ''),
  ('Genesis', 1, 3, 'And God said, Let there be light: and there was light.', 'Old', ''),
  ('Genesis', 1, 27, 'So God created man in his own image, in the image of God created he him; male and female created he them.', 'Old', ''),
  ('Exodus', 20, 3, 'Thou shalt have no other gods before me.', 'Old', ''),
  ('Exodus', 20, 12, 'Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.', 'Old', ''),
  ('Deuteronomy', 6, 5, 'And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.', 'Old', ''),
  ('Joshua', 1, 9, 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.', 'Old', ''),
  ('Psalms', 23, 1, 'The LORD is my shepherd; I shall not want.', 'Old', ''),
  ('Psalms', 46, 1, 'God is our refuge and strength, a very present help in trouble.', 'Old', ''),
  ('Psalms', 119, 105, 'Thy word is a lamp unto my feet, and a light unto my path.', 'Old', ''),
  ('Proverbs', 3, 5, 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', 'Old', ''),
  ('Proverbs', 3, 6, 'In all thy ways acknowledge him, and he shall direct thy paths.', 'Old', ''),
  ('Isaiah', 40, 31, 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', 'Old', ''),
  ('Isaiah', 41, 10, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.', 'Old', ''),
  ('Jeremiah', 29, 11, 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.', 'Old', ''),
  ('Lamentations', 3, 22, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Old', ''),
  ('Lamentations', 3, 23, 'They are new every morning: great is thy faithfulness.', 'Old', ''),
  ('Micah', 6, 8, 'He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?', 'Old', ''),
  ('Matthew', 5, 9, 'Blessed are the peacemakers: for they shall be called the children of God.', 'New', ''),
  ('Matthew', 11, 28, 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'New', ''),
  ('Matthew', 22, 37, 'Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.', 'New', ''),
  ('Matthew', 28, 19, 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:', 'New', ''),
  ('Mark', 12, 31, 'And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these.', 'New', ''),
  ('Luke', 2, 11, 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.', 'New', ''),
  ('Luke', 6, 31, 'And as ye would that men should do to you, do ye also to them likewise.', 'New', ''),
  ('John', 1, 1, 'In the beginning was the Word, and the Word was with God, and the Word was God.', 'New', ''),
  ('John', 1, 14, 'And the Word was made flesh, and dwelt among us, full of grace and truth.', 'New', ''),
  ('John', 3, 16, 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.', 'New', ''),
  ('John', 8, 12, 'I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.', 'New', ''),
  ('John', 14, 6, 'I am the way, the truth, and the life: no man cometh unto the Father, but by me.', 'New', ''),
  ('Acts', 1, 8, 'But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me.', 'New', ''),
  ('Acts', 16, 31, 'Believe on the Lord Jesus Christ, and thou shalt be saved.', 'New', ''),
  ('Romans', 8, 28, 'And we know that all things work together for good to them that love God.', 'New', ''),
  ('Romans', 10, 9, 'If thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.', 'New', ''),
  ('Romans', 12, 2, 'And be not conformed to this world: but be ye transformed by the renewing of your mind.', 'New', ''),
  ('1 Corinthians', 13, 4, 'Charity suffereth long, and is kind; charity envieth not.', 'New', ''),
  ('Galatians', 5, 22, 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.', 'New', ''),
  ('Ephesians', 2, 8, 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.', 'New', ''),
  ('Philippians', 4, 6, 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.', 'New', ''),
  ('Philippians', 4, 13, 'I can do all things through Christ which strengtheneth me.', 'New', ''),
  ('2 Timothy', 1, 7, 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', 'New', ''),
  ('2 Timothy', 3, 16, 'All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.', 'New', ''),
  ('Hebrews', 11, 1, 'Now faith is the substance of things hoped for, the evidence of things not seen.', 'New', ''),
  ('James', 1, 5, 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally.', 'New', ''),
  ('1 Peter', 5, 7, 'Casting all your care upon him; for he careth for you.', 'New', ''),
  ('1 John', 4, 8, 'God is love.', 'New', ''),
  ('Revelation', 3, 20, 'Behold, I stand at the door, and knock.', 'New', ''),
  ('Revelation', 21, 4, 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain.', 'New', '')
ON CONFLICT (book, chapter, verse) DO NOTHING;
